// Generated by scripts/generate-standing-allow-catalog.mjs — do not edit.
export interface StandingAllowCatalogShellEntry {
  command: string
  normalizedCommand: string
  runtimeKey: string
}

export interface StandingAllowCatalog {
  version: 1
  shell: {
    provablyBenign: StandingAllowCatalogShellEntry[]
    mustAllow: StandingAllowCatalogShellEntry[]
  }
}

export const STANDING_ALLOW_CATALOG: StandingAllowCatalog = {
  version: 1,
  shell: {
    provablyBenign: [
      {
        command: 'git status',
        normalizedCommand: 'git status',
        runtimeKey: '37e6be21e63e6268ee6e4212ad811f6f48ab3c3c10ce1b971c1a90d92c753a2a',
      },
      {
        command: 'rg plan src',
        normalizedCommand: 'rg plan src',
        runtimeKey: '68ae7a96158719235d9314da7b00a5f8b2f40668e5d4f7f02e91f22284140a68',
      },
      {
        command: 'ls -la',
        normalizedCommand: 'ls -la',
        runtimeKey: '3a665991b52b5f18069889960b957ea37b087859c23e2c87b76ef8d2a1b338fe',
      },
      {
        command: "find . -name '*.ts'",
        normalizedCommand: "find . -name '*.ts'",
        runtimeKey: '782298e3015fcb9c17bee2dad12a395a8859043481f93f0ca596499028bb8af2',
      },
      {
        command: 'curl https://example.com',
        normalizedCommand: 'curl https://example.com',
        runtimeKey: '09fa1bf897aa68a2d0be02cff3b0cbfa44a28fa17c501e8a39f2081208785e55',
      },
      {
        command: 'wget https://example.com',
        normalizedCommand: 'wget https://example.com',
        runtimeKey: 'c408836b4bb4498b68b52e08a7c852757a19e156cae7579ffd5c98f13728cacb',
      },
      {
        command: 'ls\ncurl https://example.com',
        normalizedCommand: 'ls\ncurl https://example.com',
        runtimeKey: 'a895f27dda259649bbe0d27fcc04ab7076fadfcd4c2ea3ab55f557028b01b11f',
      },
    ],
    mustAllow: [
      {
        command: 'npm test',
        normalizedCommand: 'npm test',
        runtimeKey: '1bcafcfef8e1b0138297885032c5e222c4aed19bdcde00e2539aa397fdc877cb',
      },
      {
        command: 'npm run build',
        normalizedCommand: 'npm run build',
        runtimeKey: '3138d8a3e9afb60574e29d16c2967f70bb42475e02eadb261f5f2340f376c188',
      },
      {
        command: 'pnpm test',
        normalizedCommand: 'pnpm test',
        runtimeKey: 'eaecc988be421de36044932e32d4be807e45baccaa94c2d29d30a34204656551',
      },
      {
        command: 'pnpm build',
        normalizedCommand: 'pnpm build',
        runtimeKey: 'a1ec94b6b1f7f17ab0fe468e41c6dc59e04266d34772abcaa9538123601cb46d',
      },
      {
        command: 'pnpm vitest run src/example.test.ts',
        normalizedCommand: 'pnpm vitest run src/example.test.ts',
        runtimeKey: '011e12e902154e7cf598f390fc08a50e885b34893deb97d242cf7470e23e617e',
      },
      {
        command: "bash -lc 'git status'",
        normalizedCommand: "bash -lc 'git status'",
        runtimeKey: 'dbcc63715f4a8cca2aff988470bb1d52a4841542af9c86776ff2414509508a1f',
      },
      {
        command: 'belay approve belay_deadbeef1234',
        normalizedCommand: 'belay approve belay_deadbeef1234',
        runtimeKey: 'bb3f0f1dac3d6c4ef79e17ef4e36f9430195596490bb736cdb8b25a5944d6f81',
      },
    ],
  },
}
