import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const { version } = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'))
writeFileSync(
  path.join(root, 'src/version.ts'),
  `// Generated by scripts/sync-version.mjs — do not edit.\nexport const PACKAGE_VERSION = '${version}'\n`,
)
