import {
  FLAGGED_COMMAND_KEYS,
  READ_ONLY_COMMAND_KEYS,
} from './command-keys.js'
import type { PolicyRule } from './types.js'

/** Built-in policy rules — same language as operator custom rules. Higher priority wins. */
export const DEFAULT_POLICY_RULES: PolicyRule[] = [
  {
    id: 'unparseable_shell',
    priority: 1000,
    nonOverridable: true,
    match: { unparseable: true },
    action: 'threshold',
    reason: 'unparseable_shell',
  },
  {
    id: 'protected_artifact',
    priority: 950,
    nonOverridable: true,
    match: { protectedArtifact: true },
    action: 'escalate',
    reason: 'control_plane_mutation',
  },
  {
    id: 'outside_repo_redirect',
    priority: 940,
    nonOverridable: true,
    match: { redirectKind: 'outside' },
    action: 'escalate',
    reason: 'outside_repo_redirect',
  },
  {
    id: 'outside_repo_mutation',
    priority: 938,
    nonOverridable: true,
    match: { outsideRepo: true },
    action: 'escalate',
    reason: 'outside_repo_mutation',
  },
  {
    id: 'dynamic_shell',
    priority: 930,
    nonOverridable: true,
    match: { signal: 'dynamic_shell_evaluation' },
    action: 'escalate',
    reason: 'dynamic_shell_evaluation',
  },
  {
    id: 'pipe_to_shell',
    priority: 920,
    nonOverridable: true,
    match: { signal: 'pipe_to_shell' },
    action: 'escalate',
    reason: 'pipe_to_shell',
  },
  {
    id: 'find_dangerous',
    priority: 900,
    nonOverridable: true,
    match: { signal: 'find_dangerous_action' },
    action: 'escalate',
    reason: 'find_dangerous_action',
  },
  {
    id: 'custom_external',
    priority: 850,
    match: { customExternal: true },
    action: 'escalate',
    reason: 'custom_external',
  },
  {
    id: 'external_effect',
    priority: 800,
    nonOverridable: true,
    match: { targetScope: 'external' },
    action: 'escalate',
    reason: 'external_effect',
  },
  {
    id: 'external_script',
    priority: 790,
    match: { commandKey: ['npm run', 'pnpm run'], signal: 'external_script_name' },
    action: 'escalate',
    reason: 'external_script',
  },
  {
    id: 'custom_allow',
    priority: 600,
    match: { customAllow: true },
    action: 'allow',
    reason: 'custom_allow',
  },
  {
    id: 'read_only',
    priority: 500,
    match: {
      commandKey: [...READ_ONLY_COMMAND_KEYS],
      redirectKind: 'none',
    },
    action: 'allow',
    reason: 'read_only',
  },
  {
    id: 'local_mutation',
    priority: 400,
    match: {
      commandKey: [...FLAGGED_COMMAND_KEYS],
    },
    action: 'flag',
    reason: 'local_mutation',
  },
  {
    id: 'unknown_local',
    priority: 100,
    match: {},
    action: 'threshold',
    reason: 'unknown_local_effect',
  },
]
